using Amazon.CDK;
using Amazon.CDK.Assertions;
using CivicBudget.Infra;

namespace CivicBudget.Infra.Tests;

/// <summary>
/// Security and cost invariants of the synthesized CloudFormation, checked without an AWS account.
/// These are the properties an interviewer (or an auditor) would ask about: is the database
/// private, can only the app reach it, do secrets stay out of the template, does it log, and can
/// the whole thing be torn down.
/// </summary>
public class CivicBudgetStackTests
{
    private static readonly Template App = Synth(new CivicBudgetStackProps { ImageTag = "abc123", AlertEmail = "ops@example.com" });

    private static Template Synth(CivicBudgetStackProps props)
    {
        var app = new App();
        var stack = new CivicBudgetStack(app, "Test", props);
        return Template.FromStack(stack);
    }

    [Fact]
    public void Database_is_private_encrypted_backed_up_and_sql_server_express()
    {
        App.HasResourceProperties("AWS::RDS::DBInstance", new Dictionary<string, object>
        {
            ["Engine"] = "sqlserver-ex",
            ["PubliclyAccessible"] = false,
            ["StorageEncrypted"] = true,
            ["BackupRetentionPeriod"] = 7,
            ["DBInstanceClass"] = "db.t3.micro",
            ["MultiAZ"] = false,
        });
        App.ResourceCountIs("AWS::RDS::DBInstance", 1);
    }

    [Fact]
    public void Database_is_reachable_only_from_the_service()
    {
        // The database security group has exactly one ingress rule, and its source is the service's
        // security group (not a CIDR); the port is the instance's own endpoint port.
        IDictionary<string, IDictionary<string, object>> ingress = App.FindResources("AWS::EC2::SecurityGroupIngress", new Dictionary<string, object>
        {
            ["Properties"] = new Dictionary<string, object> { ["Description"] = "From the CivicBudget service" },
        });

        var rule = (IDictionary<string, object>)Assert.Single(ingress).Value["Properties"];
        Assert.Equal("tcp", rule["IpProtocol"]);
        Assert.True(rule.ContainsKey("SourceSecurityGroupId"));
        Assert.False(rule.ContainsKey("CidrIp"));
        Assert.Contains("Endpoint.Port", System.Text.Json.JsonSerializer.Serialize(rule["FromPort"]), StringComparison.Ordinal);

        // And nothing opens the database to the world.
        string json = System.Text.Json.JsonSerializer.Serialize(App.FindResources("AWS::EC2::SecurityGroup"));
        Assert.DoesNotContain("1433", json, StringComparison.Ordinal);
    }

    [Fact]
    public void Task_runs_in_private_subnets_without_a_public_ip()
    {
        App.HasResourceProperties("AWS::ECS::Service", new Dictionary<string, object>
        {
            ["LaunchType"] = "FARGATE",
            ["DesiredCount"] = 1,
            ["NetworkConfiguration"] = new Dictionary<string, object>
            {
                ["AwsvpcConfiguration"] = new Dictionary<string, object> { ["AssignPublicIp"] = "DISABLED" },
            },
            ["DeploymentConfiguration"] = new Dictionary<string, object>
            {
                ["DeploymentCircuitBreaker"] = new Dictionary<string, object> { ["Enable"] = true, ["Rollback"] = true },
            },
        });
    }

    [Fact]
    public void Passwords_reach_the_container_as_secrets_never_as_environment_variables()
    {
        IDictionary<string, IDictionary<string, object>> tasks = App.FindResources("AWS::ECS::TaskDefinition");
        var properties = (IDictionary<string, object>)Assert.Single(tasks).Value["Properties"];
        var container = (IDictionary<string, object>)((object[])properties["ContainerDefinitions"])[0];

        var environment = ((object[])container["Environment"]).Cast<IDictionary<string, object>>().ToDictionary(e => (string)e["Name"], e => e["Value"]);
        var secrets = ((object[])container["Secrets"]).Cast<IDictionary<string, object>>().Select(s => (string)s["Name"]).ToList();

        Assert.Equal(["Database__Password", "Seed__DemoPassword"], secrets.Order());
        Assert.DoesNotContain("Database__Password", environment.Keys);
        Assert.DoesNotContain("Seed__DemoPassword", environment.Keys);
        Assert.DoesNotContain("ConnectionStrings__CivicBudget", environment.Keys);
        Assert.Equal("Production", environment["ASPNETCORE_ENVIRONMENT"]);
        Assert.Equal("true", environment["ASPNETCORE_FORWARDEDHEADERS_ENABLED"]);
        Assert.Equal(CivicBudgetStack.DatabaseUser, environment["Database__User"]);

        // The template never contains a literal password: the RDS secret is generated by Secrets Manager.
        string json = System.Text.Json.JsonSerializer.Serialize(App.ToJSON());
        Assert.DoesNotContain("\"MasterUserPassword\":\"", json, StringComparison.Ordinal);
    }

    [Fact]
    public void Container_logs_to_cloudwatch_with_a_retention_period()
    {
        App.HasResourceProperties("AWS::Logs::LogGroup", new Dictionary<string, object> { ["RetentionInDays"] = 30 });
        App.HasResourceProperties("AWS::ECS::TaskDefinition", new Dictionary<string, object>
        {
            ["ContainerDefinitions"] = Match.ArrayWith(
            [
                Match.ObjectLike(new Dictionary<string, object>
                {
                    ["LogConfiguration"] = Match.ObjectLike(new Dictionary<string, object> { ["LogDriver"] = "awslogs" }),
                    ["PortMappings"] = Match.ArrayWith([Match.ObjectLike(new Dictionary<string, object> { ["ContainerPort"] = CivicBudgetStack.ContainerPort })]),
                }),
            ]),
        });
    }

    [Fact]
    public void Load_balancer_is_public_checks_health_and_keeps_blazor_circuits_sticky()
    {
        App.HasResourceProperties("AWS::ElasticLoadBalancingV2::LoadBalancer", new Dictionary<string, object> { ["Scheme"] = "internet-facing" });
        App.HasResourceProperties("AWS::ElasticLoadBalancingV2::TargetGroup", new Dictionary<string, object>
        {
            ["HealthCheckPath"] = "/health",
            ["TargetGroupAttributes"] = Match.ArrayWith(
            [
                Match.ObjectLike(new Dictionary<string, object> { ["Key"] = "stickiness.enabled", ["Value"] = "true" }),
            ]),
        });
    }

    [Fact]
    public void Without_a_certificate_the_listener_is_http_and_with_one_it_is_https_with_a_redirect()
    {
        App.HasResourceProperties("AWS::ElasticLoadBalancingV2::Listener", new Dictionary<string, object> { ["Port"] = 80, ["Protocol"] = "HTTP" });
        App.ResourceCountIs("AWS::ElasticLoadBalancingV2::Listener", 1);

        Template https = Synth(new CivicBudgetStackProps { CertificateArn = "arn:aws:acm:us-east-2:123456789012:certificate/abc" });
        https.HasResourceProperties("AWS::ElasticLoadBalancingV2::Listener", new Dictionary<string, object> { ["Port"] = 443, ["Protocol"] = "HTTPS" });
        https.HasResourceProperties("AWS::ElasticLoadBalancingV2::Listener", new Dictionary<string, object>
        {
            ["Port"] = 80,
            ["DefaultActions"] = Match.ArrayWith([Match.ObjectLike(new Dictionary<string, object> { ["Type"] = "redirect" })]),
        });
    }

    [Fact]
    public void The_image_repository_comes_from_the_one_time_stack_not_this_one()
    {
        // The workflow pushes before this stack deploys; creating the repository here made a first deploy fail at the push.
        App.ResourceCountIs("AWS::ECR::Repository", 0);
    }

    [Fact]
    public void One_nat_gateway_keeps_the_bill_down()
    {
        App.ResourceCountIs("AWS::EC2::NatGateway", 1);
        App.ResourceCountIs("AWS::EC2::VPC", 1);
    }

    [Fact]
    public void Spending_alarm_exists_only_when_an_email_is_given()
    {
        App.HasResourceProperties("AWS::Budgets::Budget", new Dictionary<string, object>
        {
            ["Budget"] = Match.ObjectLike(new Dictionary<string, object>
            {
                ["BudgetLimit"] = new Dictionary<string, object> { ["Amount"] = 60, ["Unit"] = "USD" },
                ["TimeUnit"] = "MONTHLY",
            }),
        });

        Synth(new CivicBudgetStackProps()).ResourceCountIs("AWS::Budgets::Budget", 0);
    }

    [Fact]
    public void Everything_can_be_torn_down_by_cdk_destroy()
    {
        // No resource may survive a destroy and keep billing: the database and the log group delete
        // with the stack (the image repository is in GitHubOidcStack). A real deployment would flip the database.
        App.HasResource("AWS::RDS::DBInstance", new Dictionary<string, object> { ["DeletionPolicy"] = "Delete", ["UpdateReplacePolicy"] = "Delete" });
        App.HasResource("AWS::Logs::LogGroup", new Dictionary<string, object> { ["DeletionPolicy"] = "Delete" });
    }

    [Fact]
    public void Resources_are_tagged_with_the_project()
    {
        App.HasResourceProperties("AWS::EC2::VPC", new Dictionary<string, object>
        {
            ["Tags"] = Match.ArrayWith([new Dictionary<string, object> { ["Key"] = "Project", ["Value"] = "CivicBudget" }]),
        });
    }

    [Fact]
    public void Outputs_tell_the_operator_where_things_are()
    {
        App.HasOutput("ServiceUrl", Match.AnyValue());
        App.HasOutput("DemoPasswordSecretArn", Match.AnyValue());
    }
}
