<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>civicbudget-web-7c2e1b9a</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../CivicBudget.Application/CivicBudget.Application.csproj" />
    <ProjectReference Include="../CivicBudget.Infrastructure/CivicBudget.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid" />
  </ItemGroup>
</Project>
