// CivicBudget on Azure's always-free offers: a serverless Azure SQL database under the free limit
// and a Container App on the consumption plan that scales to zero, plus a scheduled job that
// rebuilds the demo database every night. Deployed into one resource group:
//   az deployment group create -g civicbudget-rg -f infra/azure/main.bicep -p sqlAdminPassword=... demoPassword=...
// The AWS CDK stack (infra/CivicBudget.Infra) remains the production-shaped story; this is the
// free showcase (ADR-0030).

targetScope = 'resourceGroup'

@description('Region. The SQL free offer and Container Apps are available in most regions; East US 2 has both.')
param location string = resourceGroup().location

@description('Prefix for every resource name.')
param namePrefix string = 'civicbudget'

@description('Container image to run, e.g. ghcr.io/spencersmithsite/civic-budget:latest. The GHCR package must be public.')
param containerImage string = 'ghcr.io/spencersmithsite/civic-budget:latest'

@description('Administrator login for the SQL logical server.')
param sqlAdminLogin string = 'civicadmin'

@secure()
@description('Administrator password for the SQL logical server. Generated by scripts/azure-setup.sh; the app reads it from a Container Apps secret.')
param sqlAdminPassword string

@secure()
@description('Password given to every seeded demo login. Published in the README on purpose; the nightly reset undoes whatever a visitor does with it.')
param demoPassword string

@description('When the nightly reset runs, as a cron expression in UTC. 08:00 UTC is 3 or 4 a.m. in Ohio.')
param resetSchedule string = '0 8 * * *'

var sqlServerName = '${namePrefix}-sql-${uniqueString(resourceGroup().id)}'
var databaseName = 'CivicBudget'
var connectionString = 'Server=tcp:${sqlServer.properties.fullyQualifiedDomainName},1433;Database=${databaseName};User ID=${sqlAdminLogin};Password=${sqlAdminPassword};Encrypt=True;TrustServerCertificate=False;Connection Timeout=60'

// ---- Logs: Container Apps requires a workspace; the first 5 GB a month are free. ----------------

resource logs 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {
  name: '${namePrefix}-logs'
  location: location
  properties: {
    sku: { name: 'PerGB2018' }
    retentionInDays: 30
    workspaceCapping: { dailyQuotaGb: 1 } // a runaway log loop cannot run up a bill
  }
}

// ---- SQL: serverless General Purpose, which is the only tier the free offer applies to. ----------
// useFreeLimit puts the database under the monthly free vCore-seconds; when they run out it pauses
// (AutoPause) rather than billing, and auto-pause after an idle hour keeps the meter still.

resource sqlServer 'Microsoft.Sql/servers@2023-08-01-preview' = {
  name: sqlServerName
  location: location
  properties: {
    administratorLogin: sqlAdminLogin
    administratorLoginPassword: sqlAdminPassword
    minimalTlsVersion: '1.2'
    publicNetworkAccess: 'Enabled'
  }
}

// Container Apps on the consumption plan have no fixed egress address, so the server admits
// connections from Azure services (0.0.0.0 is Azure's convention for that rule, not "everyone").
resource allowAzure 'Microsoft.Sql/servers/firewallRules@2023-08-01-preview' = {
  parent: sqlServer
  name: 'AllowAllWindowsAzureIps'
  properties: {
    startIpAddress: '0.0.0.0'
    endIpAddress: '0.0.0.0'
  }
}

resource database 'Microsoft.Sql/servers/databases@2023-08-01-preview' = {
  parent: sqlServer
  name: databaseName
  location: location
  sku: {
    name: 'GP_S_Gen5'
    tier: 'GeneralPurpose'
    family: 'Gen5'
    capacity: 2
  }
  properties: {
    useFreeLimit: true
    freeLimitExhaustionBehavior: 'AutoPause'
    autoPauseDelay: 60
    minCapacity: json('0.5')
    maxSizeBytes: 34359738368 // 32 GB, the free offer's ceiling
    collation: 'SQL_Latin1_General_CP1_CI_AS'
    zoneRedundant: false
    readScale: 'Disabled'
    requestedBackupStorageRedundancy: 'Local'
  }
}

// ---- Container Apps ---------------------------------------------------------------------------

resource environment 'Microsoft.App/managedEnvironments@2024-03-01' = {
  name: '${namePrefix}-env'
  location: location
  properties: {
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: logs.properties.customerId
        sharedKey: logs.listKeys().primarySharedKey
      }
    }
  }
}

// What the site and the reset job share: the image, the secrets, and the settings that make the
// image migrate and seed on start (DatabaseOptions).
var secrets = [
  { name: 'sql-connection', value: connectionString }
  { name: 'demo-password', value: demoPassword }
]
var env = [
  { name: 'ASPNETCORE_ENVIRONMENT', value: 'Production' }
  { name: 'ConnectionStrings__CivicBudget', secretRef: 'sql-connection' }
  { name: 'Database__MigrateOnStartup', value: 'true' }
  { name: 'Database__SeedDemoData', value: 'true' }
  { name: 'Seed__DemoPassword', secretRef: 'demo-password' }
]

resource app 'Microsoft.App/containerApps@2024-03-01' = {
  name: '${namePrefix}-app'
  location: location
  properties: {
    managedEnvironmentId: environment.id
    configuration: {
      ingress: {
        external: true
        targetPort: 8080
        transport: 'auto' // HTTP/1.1 and WebSockets for the Blazor circuit
        allowInsecure: false
      }
      secrets: secrets
    }
    template: {
      containers: [
        {
          name: 'web'
          image: containerImage
          resources: { cpu: json('0.25'), memory: '0.5Gi' }
          env: env
          probes: [
            {
              // /health answers as soon as Kestrel listens; the database is prepared behind it and
              // the app shows its own waiting screen meanwhile. A tight probe here is what turns a
              // scale-from-zero into a page in a few seconds rather than a hung request.
              type: 'Startup'
              httpGet: { path: '/health', port: 8080 }
              initialDelaySeconds: 2
              periodSeconds: 2
              failureThreshold: 30
            }
            {
              type: 'Liveness'
              httpGet: { path: '/health', port: 8080 }
              periodSeconds: 30
            }
          ]
        }
      ]
      // One replica at most: the output cache and the Blazor circuits live in process (ADR-0021).
      // Zero when idle, so an idle month costs nothing at all.
      scale: { minReplicas: 0, maxReplicas: 1 }
    }
  }
}

// The nightly reset: the same image with `--reseed`, on a schedule, no ingress.
resource resetJob 'Microsoft.App/jobs@2024-03-01' = {
  name: '${namePrefix}-reset'
  location: location
  properties: {
    environmentId: environment.id
    configuration: {
      triggerType: 'Schedule'
      scheduleTriggerConfig: {
        cronExpression: resetSchedule
        parallelism: 1
        replicaCompletionCount: 1
      }
      replicaTimeout: 900
      replicaRetryLimit: 1
      secrets: secrets
    }
    template: {
      containers: [
        {
          name: 'reset'
          image: containerImage
          args: ['--reseed']
          resources: { cpu: json('0.25'), memory: '0.5Gi' }
          env: env
        }
      ]
    }
  }
}

output appUrl string = 'https://${app.properties.configuration.ingress.fqdn}'
output sqlServerFqdn string = sqlServer.properties.fullyQualifiedDomainName
output appName string = app.name
output resetJobName string = resetJob.name
